# ABDULMALIK ADEDOTUN CLASS TASK 2
### Question 1
Identify the number of rows and columns in each matrix<br>
A <br>[2 -1 3]<br>
    [0  4 1]

B <br>[1 2]<br>
    [-2 0]<br>
    [5 -3]

### Answer
The first matrix A is a 2 X 3 marix, which means there are 2 rows and 3 columns<br>
The second matrix B is a 3 x 2 matrix, which means there are 3 rows and 2 columns

### Question 2
Determine whether the matrices can be multiplied. If so, specify whether it's (AB), (BA), or both.

### Answer
Matrix A is a 2 x 3 and matrix B is a 3 x 2, we check if AB is possible, the column in A must be equal to row B. Using that we can see Matrix A column is 3 and the matrix B row is 3, which means they are equal and our resulting matrix (AB) would give us a 2 x 2 matrix.

Matrix B is a 3 x 2 and matrix A is a 2 x 3, we check if BA is possible, the column in B must be equal to row A. Using that we can see Matrix B column is 2 and the matrix A row is 2, which means they are equal and our resulting matrix (BA) would give us a 3 x 3 matrix.

### Question 3
If the multiplication is defined, complete the resulting matrix.

### Answer
A <br>[2 -1 3]<br>
    [0  4 1]

B <br>[1 2]<br>
    [-2 0]<br>
    [5 -3]

AB = <br>[(2*1) + (-1*-2) + (3*5), (2*2) + (-1*0) + (3*-3)]<br>
     [(0*1) + (4*-2) + (1*5), (0*2) + (4*0) + (1*-3)]

    = [2+2+15, 4+0-9]
      [0-8+5, 0+0-3]

    = [19 -5]
      [-3 -3]

BA = <br>[(1*2) + (2*0), (1*-1) + (2*4), (1*3) + (2*1)]<br>
     [(-2*2) + (0*0), (-2*-1) + (0*4), (-2*3) + (0*1)]<br>
     [(5*2) + (-3*0), (5*-1) + (-3*4), (5*3) + (-3*1)]

    = [2+0, -1+8, 3+2]
      [-4+0, 2+0, -6+0]
      [10+0, -5-12, 15-3]

    = [2 7 5]
      [-4 2 -6]
      [10 -17 12]


In [4]:
import numpy as np

# Declaring the first matrix which is a 2 x 3 matrix
matrix_A = np.array([[2, -1, 3],
                    [0, 4, 1]])

# Declaring the second matrix which is a 3 x 2 matrix
matrix_B = np.array([[1, 2],
                    [-2, 0],
                    [5, -3]])

# multiplying matrix A by matrix B
matrix_AB = matrix_A @ matrix_B
print(f"Multiplication of matrix A by matrix B =\n{matrix_AB}")

# multiplying matrix B by matrix A
matrix_BA = matrix_B @ matrix_A
print(f"Multiplication of matrix B by matrix A =\n{matrix_BA}")



Multiplication of matrix A by matrix B =
[[19 -5]
 [-3 -3]]
Multiplication of matrix B by matrix A =
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
